### ISSUE TITLE
live-server doesnt work on arch linux, solved

### ISSUE THREAD

**Issue by maikCyphlock** [molnarmark/sublime-live-server#1]
# bad config on global node modules
the problem is that I installed it with yarn, and the server would not start, then I checked,
"**global_node_modules_path**" and found the problem, it was that the default path did not match my yarn path, which is in 

>  _"/home/work/.config/yarn/global/node_modules/",_ at least on my pc

, and when I change it to this one, the server worked, I hope this can be put in the readme.md as problems to help another one, well the server is now doing great.

**Comment by molnarmark** [comment]
Hi, thanks for the feedback.

It is indeed mentioned in the README [here](https://github.com/molnarmark/sublime-live-server#global_node_modules_path).

I'm glad to hear you solved the problem though! 🎉
