### ISSUE TITLE
Opening in non default browser

### ISSUE THREAD

**Issue by erperion** [molnarmark/sublime-live-server#10]
I have few browsers installed:
Firefox
Firefox Developer Edition
Firefox Nightly
Google Chrome
Google Chrome Dev

Firefox is my default browser, but for dev I would prefer use Firefox Developer Edition or Google Chrome Dev, but I don't know what I should put instead of "default", I tried few things like:
"browser": "firefox",
"browser": "firefox dev",
"browser": "firefox-dev",
"browser": "firefox developer",
"browser": "firefox-developer",
"browser": "mozilla-firefox-developer",
Even "google-chrome" doesn't work. I always have "Windows cannot find 'xxxxxxxxxxx'. Make sure you've typed the name correctly, then try again." So how can I open live server in non default browser?

**Comment by molnarmark** [comment]
I think if you specify the full path to the executable, that should work. I haven't done extensive testing on Windows.

**Comment by erperion** [comment]
Ok, thanks. Full path works, but I had to use double backslash to escape space, otherwise I had this error: "Error trying to parse settings: Invalid escape in Packages\User\Live-Server.sublime-settings:5:12". My settings:

```
// Live Server Settings
{
"node_executable_path": "C:/Program Files/nodejs/node.exe",
"global_node_modules_path": "C:/Users/erper/AppData/Roaming/npm/node_modules",
"browser": "C:\\Program Files\\Firefox Developer Edition\\firefox.exe",
}
```
